# Generated by Django 5.2.7 on 2025-10-31 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('promoter', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_rounds', models.IntegerField(default=10)),
                ('result_type', models.CharField(choices=[('UD', 'Unanimous Decision'), ('SD', 'Split Decision'), ('MD', 'Majority Decision'), ('KO', 'Knockout'), ('TKO', 'Technical Knockout'), ('DQ', 'Disqualification'), ('Draw', 'Draw')], max_length=10)),
                ('round_ended', models.IntegerField(blank=True, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('fighter_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_a', to='fighters.fighter')),
                ('fighter_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_b', to='fighters.fighter')),
                ('losing_fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='fighters.fighter')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fighters.weightclass')),
                ('winning_fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='fighters.fighter')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='events.event')),
            ],
        ),
    ]
