# Generated by Django 5.2.7 on 2025-10-31 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_limit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='Nigerian', max_length=50)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('reach', models.DecimalField(blank=True, decimal_places=2, help_text='Reach in cm', max_digits=5, null=True)),
                ('stance', models.CharField(choices=[('Orthodox', 'Orthodox'), ('Southpaw', 'Southpaw')], max_length=10)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('kos', models.IntegerField(default=0, help_text='Knockout wins')),
                ('biography', models.TextField(blank=True, help_text='Fighter biography and career highlights')),
                ('photo', models.ImageField(blank=True, help_text='Fighter profile photo', null=True, upload_to='fighters/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fighters.weightclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
